--2.11
CREATE TABLE PLAYER2(
PLAYER_ID CHAR(7) NOT NULL,
PLAYER_NAME VARCHAR2(20) NOT NULL,
TEAM_ID CHAR(3) NOT NULL,
E_PLAYER_NAME  VARCHAR2(40),
NICKNAME VARCHAR2(30),
JOIN_YYYY CHAR(4),
POSITION VARCHAR2(10),
BACK_NO NUMBER(2),
NATION VARCHAR2(20),
BIRTH_DATE DATE,
SOLAR CHAR(1),
HEIGHT NUMBER(3),
WEIGHT NUMBER(3),
CONSTRAINT PLAYER_PK2 PRIMARY KEY (PLAYER_ID),
CONSTRAINT PLAYER_FK2 FOREIGN KEY (TEAM_ID) 
REFERENCES TEAM(TEAM_ID)
); 

--2.12
DESC PLAYER2;

--2.13
CREATE TABLE TEAM_PAYER
AS SELECT * FROM PLAYER;

--2.14
ALTER TABLE PLAYER2 ADD (ADDRESS VARCHAR2(80));

--2.15
ALTER TABLE PLAYER2 DROP COLUMN ADDRESS;

--2.16
ALTER TABLE PLAYER2 MODIFY (JOIN_YYYY VARCHAR2(8) DEFAULT
'20020129' NOT NULL);

--2.17
ALTER TABLE PLAYER2 RENAME COLUMN PLAYER_ID TO TEMP_ID;

--2.18
ALTER TABLE PLAYER2 DROP CONSTRAINT PLAYER_FK2;

--2.19
ALTER TABLE PLAYER2 ADD CONSTRAINT PLAYER_FK2
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID);

--2.20
RENAME TEAM TO TEAM_BACKUP;

RENAME TEAM_BACKUP TO TEAM;

--2.21
DROP TABLE PLAYER2;

DESC PLAYER2;

--2.22
TRUNCATE TABLE TEAM_PLAYER;

DESC TEAM_PLAYER;

--2.24
CREATE TABLE PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200),
    AMOUNT NUMBER,
    REG_DATE DATE
);

DESC PRODUCT;

--2.27
ALTER TABLE PRODUCT ADD (PROD_DESC VARCHAR2(4000));

ALTER TABLE PRODUCT MODIFY (PRODUCT_NAME VARCHAR2(400));

DROP TABLE PRODUCT;

DROP TABLE PRODUCT PURGE;
