--3P
SELECT ENAME, COMM
FROM EMP
WHERE JOB='SALESMAN'OR JOB='MANAGER';

SELECT ENAME, COMM
FROM EMP
WHERE JOB IN('SALESMAN','MANAGER');

SELECT ENAME, NVL(COMM,100)COMMISSION
FROM EMP
WHERE JOB='SALESMAN' OR JOB='MANAGER';

--4P
SELECT ENAME,
       EMPNO,
       NULLIF(MGR,7698) NUIF
FROM EMP;

SELECT ENAME,
       EMPNO,
       MGR,
       CASE WHEN MGR=7898
        THEN NULL
        ELSE MGR
       END NUIF
FROM EMP;

--5P
SELECT MGR
FROM EMP
WHERE ENAME='KING'; -- (NULL) 출력을 통해 KING의 MGR이 없다는 사실을 알 수 있다.

SELECT MGR
FROM EMP
WHERE ENAME='JOE'; -- 아무런 값이 출력되지 않는 것을 통해 JOE라는 EMP가 없다는 사실을 알 수 있다.