--5.8
SELECT COUNT(*)"전체행수",
       COUNT(HEIGHT)"키 건수",
       MAX(HEIGHT)"최대키",
       MIN(HEIGHT)"최소키",
       ROUND(AVG(HEIGHT),2)"평균키"
FROM PLAYER
GROUP BY POSITION;

--5.9
SELECT POSITION,
       COUNT(*)"전체행수",
       COUNT(HEIGHT)"키 건수",
       MAX(HEIGHT)"최대키",
       MIN(HEIGHT)"최소키",
       ROUND(AVG(HEIGHT),2)"평균키"
FROM PLAYER
GROUP BY POSITION;

--5.10
SELECT POSITION 포지션,
       ROUND(AVG(HEIGHT),2)평균키
FROM PLAYER
GROUP BY POSITION
HAVING AVG(HEIGHT)>=180;

--5.11
SELECT POSITION 포지션,
       ROUND(AVG(HEIGHT),2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING MAX(HEIGHT) >=190;

--5.12
SELECT TEAM_ID,
       SUM(NVL(1,0))SUM
FROM PLAYER
GROUP BY TEAM_ID;

--5.13
 SELECT TEAM_ID,
SUM(NVL((CASE POSITION WHEN 'FW' THEN 1 ELSE 0 END),0)) FW, -- 이때,SUM(CASE POSITION WHEN 'FW' THEN 1 ELSE 0 END) FW와 같다 
 SUM(NVL((CASE POSITION WHEN 'MF' THEN 1 ELSE 0 END),0)) MF,
 SUM(NVL((CASE POSITION WHEN 'DF' THEN 1 ELSE 0 END),0)) DF,
 SUM(NVL((CASE POSITION WHEN 'GK' THEN 1 ELSE 0 END),0)) GK,
 SUM(NVL(1,0)) SUM
 FROM PLAYER
 GROUP BY TEAM_ID;
 
 --5.15
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE HEIGHT IS NOT NULL
ORDER BY HEIGHT DESC, BACK_NO ASC;


--5.16
SELECT PLAYER_NAME,
       POSITION,
       BACK_NO,
       HEIGHT
FROM PLAYER
WHERE HEIGHT IS NOT NULL
ORDER BY HEIGHT DESC, BACK_NO;

--5.17
SELECT DNAME, LOC, DEPTNO
FROM DEPT
ORDER BY DNAME ASC, LOC ASC, DEPTNO DESC;

SELECT DNAME, LOC, DEPTNO
FROM DEPT
ORDER BY DNAME, LOC, DEPTNO DESC;

SELECT DNAME, LOC AREA, DEPTNO
FROM DEPT
ORDER BY DNAME, AREA, DEPTNO DESC;

SELECT DNAME, LOC AREA, DEPTNO
FROM DEPT
ORDER BY 1, AREA, 3 DESC;

--5.18
SELECT ENAME, SAL -- 잘못된 예시
FROM EMP
WHERE ROWNUM < 4
ORDER BY SAL DESC;

SELECT ENAME, SAL
FROM (SELECT ENAME, SAL
      FROM EMP
      ORDER BY SAL DESC)
WHERE ROWNUM < 4;



       
       


       